apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: egressips.k8s.ovn.org
spec:
  group: k8s.ovn.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                egressIPs:
                  type: array
                  items:
                    type: string
                podSelector:
                  type: object
                namespaceSelector:
                  type: object
            status:
              type: object
  scope: Cluster
  names:
    plural: egressips
    singular: egressip
    kind: EgressIP
    shortNames:
      - eip
